name: Docker Image CI/CD to GitHub Packages

on:
  push:
    branches: [ "master" ] # Assumes 'master' is your main branch
  pull_request:
    branches: [ "master" ]

# Permissions grant the workflow the necessary access to read code and write packages
permissions:
  contents: read
  packages: write
  
env:
  REGISTRY: ghcr.io
  # This should resolve to your user/org and repo name (e.g., Apagofuegos/Synapse)
  IMAGE_NAME: ${{ github.repository }} 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long # Unique tag based on the commit hash

      - name: Build and push Docker image 🚀
        uses: docker/build-push-action@v5
        with:
          # CORRECTED PATH: Points directly to the '.' subdirectory
          context: . 
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
