name: Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            binary_name: synapse
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
            binary_name: synapse.exe
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust target
      run: rustup target add ${{ matrix.target }}
    
    - name: Install Windows toolchain
      if: matrix.target == 'x86_64-pc-windows-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64
    
    - name: Build binary
      run: cargo build --release --target ${{ matrix.target }} --bin synapse-cli
    
    - name: Strip binary (Linux)
      if: matrix.target == 'x86_64-unknown-linux-gnu'
      run: strip target/${{ matrix.target }}/release/synapse
    
    - name: Create archive
      run: |
        cd target/${{ matrix.target }}/release
        if [[ "${{ matrix.target }}" == "x86_64-unknown-linux-gnu" ]]; then
          tar czf synapse-linux-x86_64.tar.gz synapse
        else
          7z a synapse-windows-x86_64.zip synapse.exe
        fi
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/${{ matrix.target }}/release/synapse-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}